// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/userid.proto

/*
Package userid is a generated protocol buffer package.

It is generated from these files:
	proto/userid.proto

It has these top-level messages:
	Request
	Response
*/
package userid

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for UserId service

type UserIdService interface {
	GetUserId(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type userIdService struct {
	c    client.Client
	name string
}

func NewUserIdService(name string, c client.Client) UserIdService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "userid"
	}
	return &userIdService{
		c:    c,
		name: name,
	}
}

func (c *userIdService) GetUserId(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "UserId.GetUserId", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserId service

type UserIdHandler interface {
	GetUserId(context.Context, *Request, *Response) error
}

func RegisterUserIdHandler(s server.Server, hdlr UserIdHandler, opts ...server.HandlerOption) error {
	type userId interface {
		GetUserId(ctx context.Context, in *Request, out *Response) error
	}
	type UserId struct {
		userId
	}
	h := &userIdHandler{hdlr}
	return s.Handle(s.NewHandler(&UserId{h}, opts...))
}

type userIdHandler struct {
	UserIdHandler
}

func (h *userIdHandler) GetUserId(ctx context.Context, in *Request, out *Response) error {
	return h.UserIdHandler.GetUserId(ctx, in, out)
}
