version: '3.1'

services:
  user-service:
    build: ./user-service
    ports:
      - 50052:50052
    environment:
      MICRO_ADDRESS: ":50052"
      MICRO_REGISTRY: "mdns"
      DB_NAME: "golang"
      DB_HOST: "mysql"
      DB_PORT: "3306"
      DB_USER: "root"
      DB_PASSWORD: "root"
      DB_PREFIX: "go_"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.6
    ports:
      - "0.0.0.0:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root


